" Disable compatability with VI
set nocompatible

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'mattn/emmet-vim'
Plug 'StanAngeloff/php.vim'
" Colors
Plug 'tomasr/molokai'
Plug 'chriskempson/vim-tomorrow-theme'
call plug#end()

colorscheme Tomorrow-night

syntax on
filetype plugin on
filetype indent on

" General settings
set showcmd
set showmatch
set showmode
set smartcase
set smarttab
set expandtab
set softtabstop=4
set tabstop=4
set laststatus=2
set listchars=tab:▸\ ,trail:.
set ignorecase
set ruler
set autoindent
set autoread
set wrapscan
set number
set noerrorbells
set nojoinspaces
set backspace=start,indent,eol
set t_Co=256

" File locations
" Disable swap files
" Disable backup files
set directory=~/.vim/tmp
set backupdir=~/.vim/tmp
set undodir=~/.vim/tmp
set noswapfile
set nobackup
set nowritebackup
set undofile

" Indenting
autocmd FileType coffee setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType scss setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType css setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType html setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType javascript setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType json setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType less setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType php setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType python setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType yaml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab

" Removes trailing spaces
function! RemoveTrailingSpaces()
     %s/\s\+$//e
endfunction

autocmd BufWritePre * :call RemoveTrailingSpaces()
