ZSH_DISABLE_COMPFIX=true
DEFAULT_USER=zijld
ZSH_THEME="robbyrussell"
plugins=(git)

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
export PATH="/opt/homebrew/bin/":$PATH
export PATH="/Users/Shared/DBngin/mysql/8.0.33/bin":$PATH

source $ZSH/oh-my-zsh.sh

alias aliases="code ~/.zshrc"
alias hosts="sudo vim /etc/hosts"
alias a="php artisan"
alias pg_start="launchctl load ~/Library/LaunchAgents"
alias pg_stop="launchctl unload ~/Library/LaunchAgents"
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
alias mfs="php artisan migrate:fresh --seed"
alias smfs="sail artisan migrate:fresh --seed"
alias migrate="php artisan migrate"
alias smigrate="sail artisan migrate"
alias sbuildnc="sail build --no-cache"
alias sbuild="sail build"
alias test="php artisan test"
alias testp="php artisan test --parallel"
alias serve="php artisan serve"
alias watch="npm run watch"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/83/"
# Herd injected PHP binary.
export PATH="$HOME/Library/Application Support/Herd/bin/":$PATH
# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/82/"
# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/81/"
