source ~/.profile
export PATH=/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$PATH
export EDITOR='subl -w'
export PATH=~/.composer/vendor/bin:$PATH

# Git branch in prompt.

. ~/.bash_prompt

export NVM_DIR=~/.nvm
  . $(brew --prefix nvm)/nvm.sh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
